version: "3"
services:
  php:
    image: php:7.3-apache
    container_name: phpserver
    volumes:
      - ./html/:/var/www/html
    ports:
      - 8101:80

  db:
    image: mariadb:latest
    container_name: phpdb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=maindb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root